massenergize/massenergize-campaigns

src/admin-portal/create-campaign/create-technology/Info.jsx
src/admin-portal/pages/technology/new.js
src/components/admin-components/Button.jsx
src/config/environment.js
src/routes/AppRouter.js
src/utils/Constants.js

Progress on information page. 
Creating technology works.

Frimpong admin help

---

src/admin-portal/create-campaign/create-technology/Events.jsx
src/admin-portal/create-campaign/create-technology/Testimonials.jsx
src/admin-portal/create-campaign/create-technology/Vendors.jsx
src/requests/technology-requests.js
src/utils/Constants.js

This pull request fixes an issue with the testimonial update and creation functionality. The changes include updating the TechnologyEvents component to properly handle selected events, adding the Testimonials component to the create-technology page, and implementing the fetchAllTechnologyTestimonials and addTestimonials functions.

Fix testimonial update and creation

---

.eslintrc
src/admin-portal/create-campaign/create-technology/Coaches.jsx

Coaches as list

---

.github/CODE_OF_CONDUCT.md
.github/COMMIT_CONVENTION.md
.github/CONTRIBUTING.md
.github/DESC.md
.github/ISSUE_TEMPLATE.md
.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/feature.md
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/pull-request.yml
.github/workflows/push-to-main.yml
.github/workflows/version.yml
README.md
src/admin-portal/create-campaign/Managers.jsx
src/admin-portal/create-campaign/campaign-managers-view.js
src/admin-portal/create-campaign/create-technology/Incentives.jsx
src/components/admin-components/IncentivesBar.jsx
src/contexts/technology-context.js
src/hooks/use-campaign-context.js
src/hooks/use-technology-context.js
src/requests/technology-requests.js
src/views/all-campaigns-view.js

Add ability to delete incentives
Fix issue with non mutating managers list

Admin temp

---

src/views/campaign-edit-view.js

Updated 'CampaignEditView' to use useEffect for data handling and introduced a 'HorizontalPushLoader' for enhanced visual feedback. Now, the data loading process is more predictable and the loading phase is visually improved.

feat: Update data handling and loader in CampaignEditView

---

src/admin-portal/create-campaign/create-technology/Info.jsx
src/admin-portal/create-campaign/create-technology/incentive-form.js
src/views/technology-edit-view.js

This pull request fixes the image handling in the create-technology and incentive-form components. It ensures that the correct image is displayed and saved when creating or updating a technology or incentive.

Fix image handling in create-technology and incentive-form components

---

src/admin-portal/create-campaign/Managers.jsx
src/admin-portal/create-campaign/create-technology/Coaches.jsx
src/admin-portal/create-campaign/create-technology/Incentives.jsx
src/admin-portal/create-campaign/create-technology/Info.jsx
src/admin-portal/create-campaign/create-technology/Testimonials.jsx
src/admin-portal/create-campaign/create-technology/Vendors.jsx
src/admin-portal/create-campaign/create-technology/incentive-form.js
src/views/campaign-edit-view.js
src/views/technology-edit-view.js

This pull request includes the following commits:
- vendors edit
- Merge branch 'dev' of https://github.com/massenergize/massenergize-campaigns into jeph-from-dev
- vendors displayed in table format
- Refactor code: Uncomment useEffect hooks in campaign-edit-view.js and technology-edit-view.js
- Refactor campaign statistics and testimonials components
- Refactor UI layout and styles
It also includes the following file changes:
- Added hover style to .v-btn-h class
- Updated className in Incentives component
- Commented out useEffect hooks in CampaignEditView and TechnologyEditView
- Updated className in Testimonials component
- Updated variant in Testimonials component
- Commented out useEffect hooks in TechnologyEditView
- Updated className in Coaches component
- Updated className in …

Refactor code and UI layout

---

src/admin-portal/create-campaign/Events.jsx
src/admin-portal/create-campaign/campaign-details-and-preview.js
src/admin-portal/create-campaign/campaign-events-view.js
src/admin-portal/create-campaign/create-technology/Coaches.jsx
src/admin-portal/create-campaign/create-technology/Incentives.jsx
src/admin-portal/create-campaign/create-technology/Info.jsx
src/admin-portal/create-campaign/create-technology/TechnologyDeals.jsx
src/admin-portal/create-campaign/create-technology/Vendors.jsx
src/admin-portal/pages/campaign/campaign-statistics/campaign-statistics.js
src/api/urls.js
src/components/admin-components/Testimonials.jsx
src/contexts/campaign-context.js
src/requests/campaign-requests.js
src/requests/technology-requests.js
src/user-portal/pages/events/EventBox.js
src/user-portal/pages/technology/OneTechTestimonialsSection.js
src/user-portal/pages/testimonials/OneTestimonial.js
src/user-portal/pages/testimonials/TestimonialBox.js
src/user-portal/pages/testimonials/TestimonialSection.js
src/user-portal/pages/testimonials/TestimonialSectionWithFilters.js
src/views/all-campaigns-view.js
src/views/technology-edit-view.js

Fix deleting vendors and add NoItem found on deals and incentives tabs

---

src/assets/styles/mobile-only.css
src/assets/styles/pc-only.css
src/components/SmartRichText.js
src/user-portal/pages/landing-page/LandingPage.js
src/user-portal/pages/landing-page/RoamingBox.js
src/user-portal/pages/technology/GetAGreatDealSection.js
src/user-portal/pages/technology/TechnologyFullViewPage.js
src/user-portal/pages/technology/Vendors.js
src/user-portal/pages/testimonials/NewTestimonialForm.js
src/user-portal/pages/testimonials/OneTestimonial.js
src/user-portal/pages/wrappers/PageWrapper.js
src/utils/utils.js

https://github.com/massenergize/massenergize-campaigns/assets/26961591/f3e26cb5-e680-4812-9268-99d0082fc86e

Cant add link to testimonial on user side

---

src/admin-portal/create-campaign/CampaignCommunities.jsx
src/admin-portal/create-campaign/create-technology/Info.jsx
src/admin-portal/pages/campaign/campaign-statistics/campaign-statistics.js
src/components/admin-components/IncentivesBar.jsx
src/requests/campaign-requests.js
src/utils/Constants.js
src/views/technology-edit-view.js

This pull request adds a help link feature to the communities section of the campaign. It allows users to add a link to help for each community. The changes include adding a HelpLinkForm component, handling field changes, and saving the changes to the backend. The pull request also includes other minor code improvements and bug fixes.

Add help link to communities

---

src/admin-portal/pages/campaign/campaign-statistics/campaign-statistics.js
src/views/all-campaigns-view.js

This pull request updates the campaign statistics page and the all campaigns view. It includes changes to the CampaignStatistics component, the AllCampaignsView component, and related functions and styles. The changes improve the user interface and functionality of these pages.
https://github.com/massenergize/massenergize-campaigns/assets/42780120/a36e3937-053d-4ba2-a513-e20727140b21

Update campaign statistics page and all campaigns view

---

src/components/Filter.js
src/routes/AppRouter.js
src/user-portal/pages/events/EventsSectionWithFilters.js
src/user-portal/pages/landing-page/LandingPage.js
src/user-portal/pages/technology/OneTechTestimonialsSection.js
src/user-portal/pages/technology/TakeActionSection.js
src/user-portal/pages/technology/TechnologyFullViewPage.js
src/user-portal/pages/testimonials/OneTestimonial.js
src/user-portal/pages/testimonials/TestimonialSectionWithFilters.js

https://github.com/massenergize/massenergize-campaigns/assets/26961591/ea13eca2-af44-4fcd-bc99-5108816275ee

one tech page "create new testimonial" takes you to landing page form

---

src/admin-portal/create-campaign/CampaignComments.jsx
src/admin-portal/create-campaign/CampaignTestimonials.jsx
src/admin-portal/create-campaign/campaign-testimonial-view.js
src/admin-portal/create-campaign/create-technology/Testimonials.jsx
src/admin-portal/pages/campaign/campaign-statistics/campaign-statistics.js
src/assets/styles/admin-styles.scss
src/components/RenderHtml/index.js
src/components/admin-components/TestimonialCard.jsx
src/components/admin-components/Testimonials.jsx
src/requests/technology-requests.js
src/utils/Constants.js

creating testimonial page for editing campaigns

---

src/admin-portal/pages/auth/Login.js
src/api/urls.js
src/config/environment.js

small small login tweaks bi

---

src/components/admin-components/Comments.jsx

Removed debugging console.log and streamlined the process of setting the updated comments after creating a new campaign comment. This simplifies the data handling and reduces unnecessary spread operator usage.

fix: Simplify and enhance comment update in Comments.jsx

---

src/admin-portal/create-campaign/create-technology/Incentives.jsx
src/admin-portal/create-campaign/create-technology/incentive-form.js
src/components/admin-components/Comments.jsx
src/components/admin-components/IncentivesBar.jsx
src/contexts/technology-context.js
src/hooks/use-technology-context.js

Fix/comment delete UI update

---

src/admin-portal/create-campaign/create-technology/Coaches.jsx
src/admin-portal/create-campaign/create-technology/CreateVendorForm.js
src/admin-portal/create-campaign/create-technology/SectionsForm.jsx
src/admin-portal/create-campaign/create-technology/Vendors.jsx
src/components/admin-components/Button.jsx
src/components/admin-components/CustomAccordion.jsx
src/config/environment.js
src/config/firebase/admin/fire-config.js
src/guards/AuthGuard.js
src/utils/utils.js

https://github.com/massenergize/massenergize-campaigns/assets/26961591/a31733a0-8765-479c-ac64-456b37b71463

adding vendors and editing works nicely

---

src/admin-portal/create-campaign/CampaignComments.jsx
src/admin-portal/create-campaign/campaign-comment-view.js
src/admin-portal/create-campaign/campaign-testimonial-view.js
src/components/admin-components/Comments.jsx
src/components/admin-components/TestimonialCard.jsx
src/components/admin-components/Testimonials.jsx
src/requests/technology-requests.js

- on image click, displays a modal with a preview of the image

changes on testimonial card

---

src/admin-portal/create-campaign/Managers.jsx
src/admin-portal/create-campaign/campaign-managers-view.js
src/admin-portal/create-campaign/create-technology/Coaches.jsx
src/assets/styles/mobile-only.css
src/assets/styles/pc-only.css
src/user-portal/pages/banner/Banner.js
src/user-portal/pages/coaches/CoachesSectionWithFilters.js
src/user-portal/pages/events/EventsSection.js
src/user-portal/pages/events/EventsSectionWithFilters.js
src/user-portal/pages/footer/Footer.js
src/user-portal/pages/forms/CommunitySelector.js
src/user-portal/pages/forms/JoinUsForm.js
src/user-portal/pages/getting-started/GettingStartedSection.js
src/user-portal/pages/getting-started/OneBox.js
src/user-portal/pages/landing-page/LandingPage.js
src/user-portal/pages/technology/OneTechEventSection.js
src/user-portal/pages/technology/TakeActionSection.js
src/user-portal/pages/technology/Vendors.js
src/user-portal/pages/testimonials/TestimonialBox.js
src/utils/utils.js

now we can change key contact & forms clearout nicely :ok_hand:

---

src/admin-portal/create-campaign/create-technology/Coaches.jsx

add a coach clears form when edit content is in

---

src/admin-portal/create-campaign/CampaignCommunities.jsx
src/admin-portal/create-campaign/create-technology/Coaches.jsx
src/admin-portal/create-campaign/start-campaign.jsx
src/admin-portal/pages/campaign/new.js
src/contexts/campaign-context.js
src/utils/utils.js

Other fixes

---

src/admin-portal/create-campaign/campaign-events-view.js
src/admin-portal/create-campaign/create-technology/Info.jsx
src/components/admin-components/Testimonials.jsx

This commit refactors the campaign events view and create technology info components. It updates the handleRemove function in the CampaignEventsView component to correctly remove events and update the campaign technologies. It also updates the updateTechObject function in the Info component to pass the correct argument. Additionally, it adds a call to onCancel in the Testimonials component after creating a testimonial.
issue number) …

Campaign-comment-fixes

---

src/assets/styles/universal.css
src/user-portal/pages/banner/Banner.js
src/user-portal/pages/landing-page/LandingPage.js

This pull request refactors the styles in the code and adds a share button to the Banner component. Now userscan share campaignss

Campaign Share

---

src/admin-portal/create-campaign/CampaignCommunities.jsx
src/admin-portal/create-campaign/CampaignCommunitiesExtraLinks.js
src/user-portal/pages/landing-page/DoMore.js
src/user-portal/pages/landing-page/LandingPage.js

Add more community links

---

src/admin-portal/create-campaign/campaign-events-view.js

This pull request adds a loading indicator and fixes a dependency issue in the useEffect hook.

Add loading indicator and fix useEffect dependency

---

src/api/urls.js

…. However, based on the provided code, a suitable commit message could be:
Update production API endpoint URL
The API endpoint URL in a production environment was slightly altered by removing the trailing slash. This ensures that the URLs are consistent and could potentially solve any issues caused by different handling of these two variations of URLs.
issue number)

hot-fix: correct API base url with duplicating trailing slash

---

public/index.html

- content description changed
- link icon changed
issue number)

index.html edit

---

src/user-portal/pages/footer/Footer.js

This pull request updates the button styles in the Footer.js file. The background color of the buttons is changed to white and the text color is changed to black. This improves the overall appearance and readability of the buttons.

Update button styles in Footer.js

---

src/admin-portal/create-campaign/CampaignCommunities.jsx
src/assets/styles/universal.css
src/user-portal/pages/coaches/CoachesSectionWithFilters.js
src/user-portal/pages/technology/OneTechMeetTheCoachesSetion.js

This pull request includes changes to update the button label and styles in the Footer and Navbar components. The button label in the Footer component has been changed to "Submit" and the button styles in both the Footer and Navbar components have been updated to have a white background and black text color.

Update button label and styles in Footer and Navbar components

---

src/user-portal/pages/banner/Banner.js
src/user-portal/pages/landing-page/LandingPage.js

⚠️ NB: The other functionalities listed on the ticket already exist! Clicking on the items on the navigation takes you to the right areas on the individual technology pages. 
#158

Navigating to "home" takes you to the top

---

src/user-portal/pages/footer/Footer.js

Add community links to footer menu

---

src/user-portal/pages/footer/Footer.js
src/user-portal/pages/forms/JoinUsForm.js
src/user-portal/pages/landing-page/LandingPage.js

Bottom technologies menu items now scrolls to getting started etc

---

src/assets/styles/pc-only.css
src/user-portal/pages/coaches/CoachesSection.js
src/user-portal/pages/coaches/CoachesSectionWithFilters.js
src/user-portal/pages/technology/OneTechMeetTheCoachesSetion.js

Update coach section styles and descriptions

---

src/components/navbar/AppNavigationBar.js
src/user-portal/pages/footer/Footer.js
src/user-portal/pages/landing-page/LandingPage.js
src/user-portal/pages/technology/OneTechTestimonialsSection.js
src/user-portal/pages/technology/TechnologyFullViewPage.js
src/utils/utils.js

…cutoff, and now allows scroll
issue number)
https://github.com/massenergize/massenergize-campaigns/assets/26961591/a7bb4ce5-44ae-4b11-8e7e-e1b9b501ed8f
#158  #162

Scroll goes to actual section (Visually) #158, #162

---

src/assets/styles/pc-only.css
src/components/navbar/AppNavigationBar.js
src/user-portal/pages/banner/HeroWithBelt.js
src/user-portal/pages/events/OneEvent.js
src/user-portal/pages/landing-page/LandingPage.js
src/user-portal/pages/technology/TechnologyFullViewPage.js

Dev
issue number)
https://github.com/massenergize/massenergize-campaigns/assets/26961591/f63c35c3-3672-43b3-bbfb-88c23ba33e8d

Hero area version 2

---

src/user-portal/pages/banner/Banner.js
src/user-portal/pages/banner/Hero.js
src/user-portal/pages/banner/HeroWithBelt.js
src/user-portal/pages/landing-page/LandingPage.js

campaign not live location moved

---

src/user-portal/pages/landing-page/LandingPage.js
src/user-portal/pages/technology/TakeActionSection.js

…ok_hand:
issue number)
#171 , #176

Chore (user-side): add take action space reduction and color change 

---

src/assets/styles/pc-only.css
src/user-portal/pages/technology/TakeActionSection.js
src/user-portal/pages/technology/TechnologyFullViewPage.js

Fix: Font increase for tech, and button alignment

---

src/user-portal/pages/testimonials/NewTestimonialForm.js

hot-fix/Aliases-on-campaign

---

src/utils/utils.js

Two new utility functions have been added to the utils.js file. These functions, formatTime and formatDate, allow for customizable date and time formatting throughout the application.
issue number)

fix: Add date and time formatting utilities

---

src/user-portal/pages/getting-started/GettingStartedSection.js
src/user-portal/pages/getting-started/OneBox.js
src/utils/utils.js

Dev to canary

---

src/components/navbar/AppNavigationBar.js

The content positioning in the Navbar was modified from "justify-content-between" to "justify-content-center". Additionally, the logo width was directly set to 140, replacing the previous max-width value. This ensures the Navbar components are centralized and the logo maintains consistent sizing.
issue number)

Update Navbar layout and logo size

---

src/assets/styles/mobile-only.css
src/assets/styles/styles.scss
src/components/navbar/AppNavigationBar.js
src/user-portal/pages/getting-started/GettingStartedSection.js
src/user-portal/pages/getting-started/NewOneBox.js
src/user-portal/pages/technology/TakeActionSection.js

feat: Update style and layout for responsiveness

---

src/components/navbar/AppNavigationBar.js

The maxWidth property has been set in the AppNavigationBar's container. This fixes an alignment issue in medium-sized devices and enhances the overall visual sequence. This update helps improve the aesthetics of the user interface and makes it easier to navigate.
issue number)

fix: set maxWidth in AppNavigationBar container

---

src/user-portal/pages/forms/CommunitySelector.js
src/user-portal/pages/forms/GetHelpForm.js

fix (user-side): Add coach help ink fix and different fallback form link

---

src/user-portal/pages/events/OneEvent.js

Fix (user-side) : Add navbar fix for one event page

---

src/user-portal/pages/events/OneEvent.js

Fix (user-side): Remove img take entirely if there is no URL

---

src/admin-portal/create-campaign/Information.jsx

chore: Add space between about us title box and description box

---

public/index.html
src/api/urls.js

Feature: Add PROD analytics

---

src/user-portal/pages/events/OneEvent.js

fix: Remove fallback when no image, and make image end to end

---

src/admin-portal/create-campaign/Information.jsx

fix: Make about us title only show locally or on dev

---

src/admin-portal/create-campaign/Information.jsx

feat: Revert conditional about us title feature

---

src/admin-portal/create-campaign/Partners.jsx
src/admin-portal/create-campaign/create-technology/Coaches.jsx
src/assets/styles/styles.scss
src/components/admin-components/Input.jsx
src/components/admin-components/TestimonialCard.jsx
src/components/admin-components/Testimonials.jsx
src/utils/utils.js

issue number)
https://github.com/massenergize/massenergize-campaigns/assets/26961591/0971b64b-b991-48be-b262-28d805ceaeae

Feat : Email & Phone number validation

---

src/user-portal/pages/events/EventsSectionWithFilters.js
src/utils/utils.js

fix: events are now arranged in order of upcoming

---

.github/workflows/add-tags-on-merge.yaml
.github/workflows/deployment.yaml
src/admin-portal/pages/auth/Login.js
src/api/urls.js
src/config/config.json
src/user-portal/pages/footer/Footer.js

chore: Setup better ci cd

---

.github/workflows/pull-request.yml

chore: Update pull-request.yml

---

.github/workflows/add-tags-on-merge.yaml

chore: fix add-tags-on-merge workflow to target correct branch name

---

src/user-portal/pages/forms/JoinUsForm.js

issue number)
https://github.com/massenergize/massenergize-campaigns/assets/42780120/3d2ccb6d-aed8-4b6f-ada5-0cc304f990b1

fix(#994):Added Notifications for Failed Campaign Subscription API Calls

---

src/admin-portal/create-campaign/Information.jsx

Fix for this: https://github.com/massenergize/massenergize-campaigns/pull/298
issue number)

Fix-date-field-changing-to-text

---

src/components/admin-components/Testimonials.jsx

Fix for this : #287 
issue number)

feat: adding testimonial now works

---

src/user-portal/pages/forms/CommunitySelector.js
src/user-portal/pages/forms/JoinUsForm.js

https://github.com/massenergize/massenergize-campaigns/assets/26961591/94876652-2f52-4efe-96e6-6dba35a2b7f3
issue number)

fix:  community selection is now required before subscription

---

src/user-portal/pages/events/EventBox.js
src/user-portal/pages/events/OneEvent.js
src/user-portal/pages/landing-page/DoMore.js
src/utils/utils.js

feat: Add time to one event page & change image on event card to contain

---

src/admin-portal/create-campaign/Information.jsx
src/components/admin-components/Input.jsx

1. Information.jsx (src/admin-portal/create-campaign/Information.jsx)
2. Input.jsx (src/components/admin-components/Input.jsx)
Edited the condition for rendering the date inputs
issue number)

Rendering of date fields in the campaign's admin page

---

src/user-portal/pages/events/AddToGoogleCalendar.js
src/user-portal/pages/events/ICSEventCreator.js

issue number)
https://github.com/massenergize/massenergize-campaigns/assets/42780120/6d4126a8-037b-4920-8ae4-cc3f62bad0a2

Fix: Add to calendar location showing as [obj obj]

---

src/api/messenger.js
src/redux/actions/actions.js

More-translation-twists-and-turns

---

src/api/messenger.js

Fix: Language not being sent to backend

---

src/api/messenger.js
src/components/data-table/TableFilters.js
src/components/language/LanguageSelector.js
src/helpers/utils/index.js
src/helpers/utils/string.js
src/utils/utils.js

issue number)
This PR addresses

Feat: Pause translation for campaign admin site

---

src/user-portal/pages/commenting/CommentComponentForModal.js
src/user-portal/pages/events/ICSEventCreator.js
src/user-portal/pages/forms/JoinUsForm.js
src/user-portal/pages/technology/CommentDeleteConfirmation.js
src/user-portal/pages/technology/TechnologyFullViewPage.js
src/utils/internationalization/json-statics.js

Fix: Untranslated areas

---

src/user-portal/pages/coaches/CoachesSectionWithFilters.js
src/user-portal/pages/commenting/CommentComponentForModal.js
src/user-portal/pages/footer/Footer.js
src/user-portal/pages/getting-started/GettingStartedSection.js
src/user-portal/pages/technology/OneTechMeetTheCoachesSetion.js
src/user-portal/pages/technology/TechnologyFullViewPage.js
src/user-portal/pages/testimonials/NewTestimonialForm.js
src/user-portal/pages/testimonials/TestimonialBox.js
src/utils/internationalization/json-statics.js

issue number)
This PR fixes the following translation issues and more:

fix: Static texts translation

---

.github/workflows/deployment.yaml
src/config/config.json

Add TinyMCE Env reference to GH Action 

---

src/assets/styles/tablet-ish.css
src/components/navbar/AppNavigationBar.js

Add TinyMCE Keys

---

.github/workflows/add-tags-on-merge.yaml

Introducing the one branch system

---

src/admin-portal/create-campaign/create-technology/CallToActionForm.jsx
src/admin-portal/create-campaign/create-technology/Info.jsx
src/components/themes/sptV2/SPTV2AboutSection.js

issue number)
This PR adds call-to-action button customization to technology.

Feat: add call to action to technology.

---

src/admin-portal/create-campaign/create-technology/Incentives.jsx

issue number)
This PR introduces a new CustomAccordion component allowing for the customization of the technology overview title.

Add title customization for technology overview

---

.github/workflows/deployment.yaml
src/components/admin-components/RichText.jsx

Fix: Tinymce key issue fix

---

src/admin-portal/create-campaign/CampaignInformation.jsx
src/admin-portal/themes/theme-configurations.js
src/assets/styles/pc-only.scss
src/components/admin-components/RichText.jsx
src/components/pieces/Loading.js
src/components/themes/sptV2/SPTContactSection.js
src/components/themes/sptV2/SPTV2Entry.js
src/user-portal/pages/events/OneEvent.js
src/user-portal/pages/landing-page/LandingPage.js
src/utils/internationalization/json-statics.js

Fix - Translation and many other tweaks after tests

---

src/api/urls.js
src/assets/styles/mobile-only.css
src/assets/styles/pc-only.scss
src/components/themes/sptV2/SPTContactSection.js
src/components/themes/sptV2/SPTV2Entry.js
src/index.css
src/user-portal/pages/events/EventBox.js

Feature: floating contact us now setup

---

src/components/page-builder/PBEntry.js
src/components/page-builder/components/floating-footer/PBFloatingFooter.js
src/components/page-builder/utils/engine/blocks.js
src/components/page-builder/utils/engine/data.js

This pull request includes several updates to the page builder components and their associated styles. The most significant changes involve adding a save functionality to the `PBFloatingFooter` component and adjusting the default styles for various blocks.
Enhancements to `PBFloatingFooter`:
* [`src/components/page-builder/PBEntry.js`](diffhunk://#diff-499500b8ef318f91a122128f5ff60cf4c2cdb3fde0d5bfcb78cd96cb2067eb2fL137-R141): Added a `save` prop to the `PBFloatingFooter` component, which logs the final payload when invoked.
* [`src/components/page-builder/components/floating-footer/PBFloatingFooter.js`](diffhunk://#diff-25832afb8be5f8ae7dac285ea89fd58aae96697c0d2b72f9f03f73af88040fccL3-R3): Modified the `PBFloatingFooter` component to accept a `save` prop and execute it when the save …

light tweaks
